# Setup
title: Sam Frederick
url: https://samfrederick.github.io/
paginate: 1
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Sam Frederick
  url: 'https://samfrederick.github.io/'
  email: astronofrederick@gmail.com

pages_list:
  About: '/about'
  Projects: '/projects'
